import torch
import torch.nn.functional as F
from transformers import PreTrainedModel, PreTrainedTokenizer
from typing import List, Dict, Optional, Union
import logging

logger = logging.getLogger(__name__)

def calculate_da_reward(
    prompts_input_ids: torch.Tensor,        # Renamed from prompts, expects Tensor (Batch, PromptSeqLen)
    student_sequences: torch.Tensor,      # Renamed from student_responses, expects Full Tensor (Batch, FullSeqLen)
    teacher_model: PreTrainedModel,
    teacher_tokenizer: PreTrainedTokenizer,
    device: torch.device,
    lambda_da: float,
    intrinsic_reward_weight: float,
    intrinsic_rewards: Optional[List[float]] = None,
    da_reward_type: str = "log_likelihood",
    ll_batch_size: int = 4,
) -> List[float]:
    """
    Calculates the distillation alignment (DA) reward, potentially combining
    teacher log-likelihood with intrinsic rewards.

    Args:
        prompts_input_ids: Token IDs of the original prompts (Tensor).
        student_sequences: Full sequences (prompt + completion) generated by the student (Tensor).
        teacher_model: The teacher language model.
        teacher_tokenizer: The teacher model's tokenizer.
        device: The torch device ('cuda' or 'cpu').
        lambda_da: Weight for the distillation reward component.
        intrinsic_reward_weight: Weight for the intrinsic reward component.
        intrinsic_rewards: Optional list of intrinsic rewards for the batch.
        da_reward_type: Type of DA reward to calculate ('log_likelihood', ...).
        ll_batch_size: Batch size to use for internal log-likelihood calculation if needed.

    Returns:
        A list of float values, representing the total calculated reward for each sequence.
    """

    if da_reward_type == "log_likelihood":
        da_rewards = calculate_log_likelihood_reward(
            prompts_input_ids=prompts_input_ids,
            student_sequences=student_sequences,
            teacher_model=teacher_model,
            teacher_tokenizer=teacher_tokenizer,
            device=device,
            batch_size=ll_batch_size
        )
    else:
        logger.warning(f"Unsupported da_reward_type: '{da_reward_type}'. Defaulting DA reward to 0.")
        da_rewards = [0.0] * prompts_input_ids.shape[0]

    total_rewards = []
    batch_size = prompts_input_ids.shape[0]

    if intrinsic_rewards is None:
        intrinsic_rewards = [0.0] * batch_size
    elif len(intrinsic_rewards) != batch_size:
        logger.warning(f"Length mismatch: intrinsic_rewards ({len(intrinsic_rewards)}) vs batch_size ({batch_size}). Using 0 for intrinsic.")
        intrinsic_rewards = [0.0] * batch_size

    if len(da_rewards) != batch_size:
         logger.error(f"Length mismatch: da_rewards ({len(da_rewards)}) vs batch_size ({batch_size}). Cannot combine. Returning zeros.")
         return [0.0] * batch_size

    for intr_reward, da_reward in zip(intrinsic_rewards, da_rewards):
        combined = (intrinsic_reward_weight * float(intr_reward)) + (lambda_da * float(da_reward))
        total_rewards.append(combined)

    return total_rewards

def calculate_log_likelihood_reward(
    prompts_input_ids: torch.Tensor,
    student_sequences: torch.Tensor,
    teacher_model: PreTrainedModel,
    teacher_tokenizer: PreTrainedTokenizer,
    device: torch.device,
    batch_size: int = 4
) -> List[float]:
    actual_batch_size = student_sequences.shape[0]
    prompt_seq_len = prompts_input_ids.shape[1]
    full_seq_len = student_sequences.shape[1]
    completion_seq_len = full_seq_len - prompt_seq_len

    if completion_seq_len <= 0:
        logger.debug("No completion tokens found, returning zero log-likelihood.")
        return [0.0] * actual_batch_size

    teacher_model.eval()
    all_sequence_log_likelihoods = []

    for i in range(0, actual_batch_size, batch_size):
        mini_batch_indices = slice(i, min(i + batch_size, actual_batch_size))
        mini_batch_student_seq = student_sequences[mini_batch_indices].to(device)
        mini_batch_prompt_ids = prompts_input_ids[mini_batch_indices]

        current_mini_batch_size = mini_batch_student_seq.shape[0]

        with torch.no_grad():
            pad_token_id = teacher_tokenizer.pad_token_id or teacher_tokenizer.eos_token_id
            if pad_token_id is None:
                 logger.error("Teacher tokenizer has no pad or EOS token ID. Cannot create attention mask.")
                 return [0.0] * actual_batch_size

            attention_mask = mini_batch_student_seq.ne(pad_token_id).to(device)
            outputs = teacher_model(mini_batch_student_seq, attention_mask=attention_mask)
            logits = outputs.logits

            shift_logits = logits[:, prompt_seq_len-1:-1, :]
            shift_labels = mini_batch_student_seq[:, prompt_seq_len:]

            vocab_size = shift_logits.size(-1)
            log_probs = -F.cross_entropy(shift_logits.reshape(-1, vocab_size), shift_labels.reshape(-1), reduction='none')
            log_probs = log_probs.reshape(current_mini_batch_size, completion_seq_len)

            completion_pad_mask = shift_labels.eq(pad_token_id)
            log_probs.masked_fill_(completion_pad_mask, 0.0)

            sequence_log_likelihoods = log_probs.sum(dim=1)
            all_sequence_log_likelihoods.extend(sequence_log_likelihoods.cpu().tolist())

        del mini_batch_student_seq, outputs, logits, shift_logits, shift_labels, log_probs, attention_mask
        if device.type == 'cuda': torch.cuda.empty_cache()

    if len(all_sequence_log_likelihoods) != actual_batch_size:
         logger.error(f"Log likelihood calculation error: Expected {actual_batch_size} results, got {len(all_sequence_log_likelihoods)}.")
         return [0.0] * actual_batch_size

    return all_sequence_log_likelihoods

# Keep the conceptual example commented out or remove
# def calculate_total_reward(...): ...


